version: '3.7'
services:
  gazebo:
    image: mcognie/maximecognie-cp22:tortoisebot-ros2-gazebo
    build:
      context: .
      dockerfile: tortoisebot_gazebo.Dockerfile
    hostname: gazebo
    restart: always
    environment: 
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  
  slam:
    image: mcognie/maximecognie-cp22:tortoisebot-ros2-slam
    build:
      context: .
      dockerfile: tortoisebot_slam.Dockerfile
    hostname: slam
    restart: always
  
  rviz:
    image: mcognie/maximecognie-cp22:tortoisebot_base_ros2
    hostname: rviz
    restart: always
    environment: 
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash -c "source install/setup.bash && ros2 launch tortoisebot_description rviz.launch.py"